#!/bin/sh

set -e

BetopiaERP_LIB_DIR=/var/lib/BetopiaERP
BetopiaERP_USER="BetopiaERP"
BetopiaERP_GROUP="BetopiaERP"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    remove)
        deluser --quiet --system $BetopiaERP_USER || true
        delgroup --quiet --system --only-if-empty $BetopiaERP_GROUP || true
        	# remove workaround for https://bugs.debian.org/1059326
        if [ -L ${GSFONTS_DIR}/n021003l.pfb ] ; then
            rm ${GSFONTS_DIR}/n021003l.pfb
            if [ "$(ls -A ${GSFONTS_DIR})" = ".created-by-BetopiaERP-package" ] ; then
                rm -fr ${GSFONTS_DIR}
            fi
    	fi
        ;;

    purge)
        if [ -d "$BetopiaERP_LIB_DIR" ]; then
            rm -rf $BetopiaERP_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
