#!/bin/sh

set -e

BETOPIAERP_LIB_DIR=/var/lib/betopiaerp
BETOPIAERP_USER="betopiaerp"
BETOPIAERP_GROUP="betopiaerp"
GSFONTS_DIR=/usr/share/fonts/type1/gsfonts

case "${1}" in
    remove)
        deluser --quiet --system $BETOPIAERP_USER || true
        delgroup --quiet --system --only-if-empty $BETOPIAERP_GROUP || true
        	# remove workaround for https://bugs.debian.org/1059326
        if [ -L ${GSFONTS_DIR}/n021003l.pfb ] ; then
            rm ${GSFONTS_DIR}/n021003l.pfb
            if [ "$(ls -A ${GSFONTS_DIR})" = ".created-by-betopiaerp-package" ] ; then
                rm -fr ${GSFONTS_DIR}
            fi
    	fi
        ;;

    purge)
        if [ -d "$BETOPIAERP_LIB_DIR" ]; then
            rm -rf $BETOPIAERP_LIB_DIR
        fi
        ;;

    upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        ;;

esac

#DEBHELPER#

exit 0
